"""init schema

Revision ID: 1127baad37c9
Revises: 
Create Date: 2026-06-05 19:42:34.064937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1127baad37c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index(op.f('ix_problems_topic'), 'problems', ['topic'], unique=False)
    op.create_table('attempts',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_attempts_problem_id_problems')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_problem_id'), 'attempts', ['problem_id'], unique=False)
    op.create_table('steps',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_before', sa.Text(), nullable=True),
    sa.Column('normalized_after', sa.Text(), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('diagnostics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_steps_attempt_id_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steps'))
    )
    op.create_index(op.f('ix_steps_attempt_id'), 'steps', ['attempt_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('soft_score', sa.Float(), nullable=False),
    sa.Column('math_score', sa.Float(), nullable=False),
    sa.Column('logic_score', sa.Float(), nullable=False),
    sa.Column('condition_score', sa.Float(), nullable=False),
    sa.Column('goal_score', sa.Float(), nullable=False),
    sa.Column('error_probs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_analysis_results_step_id_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    op.create_index(op.f('ix_analysis_results_step_id'), 'analysis_results', ['step_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_step_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_steps_attempt_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_attempts_problem_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_problems_topic'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
