"""add student profile

Revision ID: 1344f683c1b4
Revises: 1127baad37c9
Create Date: 2026-06-25 15:58:17.730652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1344f683c1b4'
down_revision: Union[str, Sequence[str], None] = '1127baad37c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('profile_key', sa.String(length=100), nullable=False),
    sa.Column('overall_mastery', sa.Float(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('correct_steps', sa.Integer(), nullable=False),
    sa.Column('incorrect_steps', sa.Integer(), nullable=False),
    sa.Column('topic_mastery_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misconception_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles'))
    )
    op.create_index(op.f('ix_student_profiles_profile_key'), 'student_profiles', ['profile_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_profile_key'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
